/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : dmaController1.h
**     Project     : LPUART_Example
**     Processor   : S32K144_100
**     Component   : fsl_edma
**     Version     : Component S32K144_SDK02, Driver 01.00, CPU db: 3.00.000
**     Repository  : S32K144_SDK02
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-03-05, 15:58, # CodeGen: 0
**     Contents    :
**         EDMA_DRV_Init                        - edma_status_t EDMA_DRV_Init(edma_state_t * edmaState,const edma_user_config_t...
**         EDMA_DRV_Deinit                      - edma_status_t EDMA_DRV_Deinit(void);
**         EDMA_DRV_ChannelInit                 - edma_status_t EDMA_DRV_ChannelInit(edma_chn_state_t * edmaChannelState,const...
**         EDMA_DRV_RequestChannel              - edma_status_t EDMA_DRV_RequestChannel(uint8_t...
**         EDMA_DRV_ReleaseChannel              - edma_status_t EDMA_DRV_ReleaseChannel(edma_chn_state_t * chn);
**         EDMA_DRV_StartChannel                - edma_status_t EDMA_DRV_StartChannel(edma_chn_state_t * chn);
**         EDMA_DRV_StopChannel                 - edma_status_t EDMA_DRV_StopChannel(edma_chn_state_t * chn);
**         EDMA_DRV_InstallCallback             - edma_status_t EDMA_DRV_InstallCallback(edma_chn_state_t * chn,edma_callback_t...
**         EDMA_DRV_IRQHandler                  - void EDMA_DRV_IRQHandler(uint8_t channel);
**         EDMA_DRV_ErrorIRQHandler             - void EDMA_DRV_ErrorIRQHandler(void);
**         EDMA_DRV_GetChannelStatus            - static inline edma_chn_status_t EDMA_DRV_GetChannelStatus(edma_chn_state_t *...
**         EDMA_DRV_PushConfigToReg             - edma_status_t EDMA_DRV_PushConfigToReg(edma_chn_state_t *...
**         EDMA_DRV_PushConfigToSTCD            - void EDMA_DRV_PushConfigToSTCD(edma_chn_state_t * chn,edma_transfer_config_t...
**         EDMA_DRV_ConfigSingleBlockTransfer   - edma_status_t EDMA_DRV_ConfigSingleBlockTransfer(edma_chn_state_t *...
**         EDMA_DRV_ConfigLoopTransfer          - edma_status_t EDMA_DRV_ConfigLoopTransfer(edma_chn_state_t *...
**         EDMA_DRV_ConfigScatterGatherTransfer - edma_status_t EDMA_DRV_ConfigScatterGatherTransfer(edma_chn_state_t *...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file dmaController1.h
** @version 01.00
*/         
/*!
**  @addtogroup dmaController1_module dmaController1 module documentation
**  @{
*/         
#ifndef dmaController1_H
#define dmaController1_H
/* MODULE dmaController1. */

/* Include inherited beans */
#include "clockMan1.h"
#include "osif1.h"
#include "Cpu.h"

/*! @brief Driver state structure which holds driver runtime data */
extern edma_state_t dmaController1_State;

/*! @brief eDma channel state structure 0. Holds channel runtime data */
extern edma_chn_state_t dmaController1Chn0_State;

/*! @brief Configuration declaration */
extern const edma_user_config_t dmaController1_InitConfig0;
    
/*! @brief eDma channel configuration 0 */
extern const edma_channel_config_t dmaController1Chn0_Config;


#endif  /* ifndef dmaController1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
