/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : osif1.h
**     Project     : LPUART_Example
**     Processor   : S32K144_100
**     Component   : fsl_osif
**     Version     : Component S32K144_SDK02, Driver 01.00, CPU db: 3.00.000
**     Repository  : S32K144_SDK02
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-03-05, 15:58, # CodeGen: 0
**     Contents    :
**         OSIF_TimeDelay    - void OSIF_TimeDelay(const uint32_t delay);
**         OSIF_MutexLock    - osif_status_t OSIF_MutexLock(const mutex_t *const pMutex,const uint32_t...
**         OSIF_MutexUnlock  - osif_status_t OSIF_MutexUnlock(const mutex_t *const pMutex);
**         OSIF_MutexCreate  - osif_status_t OSIF_MutexCreate(mutex_t *const pMutex);
**         OSIF_MutexDestroy - osif_status_t OSIF_MutexDestroy(const mutex_t *const pMutex);
**         OSIF_SemaWait     - osif_status_t OSIF_SemaWait(semaphore_t *const pSem,const uint32_t timeout);
**         OSIF_SemaPost     - osif_status_t OSIF_SemaPost(semaphore_t *const pSem);
**         OSIF_SemaCreate   - osif_status_t OSIF_SemaCreate(semaphore_t *const pSem,const uint8_t initValue);
**         OSIF_SemaDestroy  - osif_status_t OSIF_SemaDestroy(const semaphore_t *const pSem);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file osif1.h
** @version 01.00
*/         
/*!
**  @addtogroup osif1_module osif1 module documentation
**  @{
*/         
#ifndef osif1_H
#define osif1_H
/* MODULE osif1. */
/* Include inherited beans */
#include "clockMan1.h"
#include "Cpu.h"
#include "fsl_osif.h"

/*! @brief Device instance number */


/* This file is generated automatically by OS Interface layer and is intentionally
    left empty */

#endif
/* ifndef osif1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/
